plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ktg.whitelotus'
    compileSdk 35

    sourceSets {
        main {
            assets.srcDirs = ['../site']
        }
    }

    defaultConfig {
        applicationId 'com.ktg.whitelotus'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
